# Generated by Django 3.2.12 on 2023-11-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_watch_quantity_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
